services:
  - type: web
    name: nexturn-final
    env: go
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    autoDeploy: true
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
