services:
  - type: web
    name: nexturn-final
    env: go
    buildCommand: go build -o app .
    startCommand: ./app
    buildFilterPath: cmd/server
    autoDeploy: true
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
